{
  "cells": [
    {
      "cell_type": "code",
      "source": [
        "import json\n",
        "import re\n",
        "import collections\n",
        "import os\n",
        "from pathlib import Path\n",
        "\n",
        "def extract_hanja(text):\n",
        "    \"\"\"\n",
        "    텍스트에서 한자(CJK Unified Ideographs)만 추출\n",
        "    \"\"\"\n",
        "    # CJK Unified Ideographs 범위: U+4E00-U+9FFF\n",
        "    hanja_pattern = re.compile(r'[\\u4e00-\\u9fff]')\n",
        "    hanja_chars = hanja_pattern.findall(text)\n",
        "    return ''.join(hanja_chars)\n",
        "\n",
        "def generate_ngrams(text, n):\n",
        "    \"\"\"\n",
        "    문자열로부터 n-그램 생성\n",
        "    \"\"\"\n",
        "    return [text[i:i+n] for i in range(len(text) - n + 1)]\n",
        "\n",
        "def process_text_file(file_path):\n",
        "    \"\"\"\n",
        "    텍스트 파일 처리\n",
        "    \"\"\"\n",
        "    try:\n",
        "        with open(file_path, 'r', encoding='utf-8') as f:\n",
        "            content = f.read()\n",
        "    except UnicodeDecodeError:\n",
        "        try:\n",
        "            with open(file_path, 'r', encoding='cp949') as f:\n",
        "                content = f.read()\n",
        "        except Exception as e:\n",
        "            print(f\"파일 읽기 오류 ({file_path}): {e}\")\n",
        "            return collections.Counter()\n",
        "\n",
        "    # 한자만 추출\n",
        "    all_hanja = extract_hanja(content)\n",
        "\n",
        "    if not all_hanja:\n",
        "        print(f\"'{file_path}'에서 한자를 찾을 수 없습니다.\")\n",
        "        return collections.Counter()\n",
        "\n",
        "    print(f\"'{file_path}' - 추출된 한자 수: {len(all_hanja)}\")\n",
        "\n",
        "    # 2-그램 생성\n",
        "    bigrams = generate_ngrams(all_hanja, 2)\n",
        "\n",
        "    if not bigrams:\n",
        "        print(f\"'{file_path}' - 생성된 2-그램이 없습니다.\")\n",
        "        return collections.Counter()\n",
        "\n",
        "    # 빈도수 계산\n",
        "    bigram_counts = collections.Counter(bigrams)\n",
        "\n",
        "    return bigram_counts\n",
        "\n",
        "def save_bigrams_to_file(bigram_counts, file_path='hanja_bigram_counts_all.txt'):\n",
        "    \"\"\"모든 2-그램 빈도수를 파일로 저장\"\"\"\n",
        "    if not bigram_counts:\n",
        "        print(\"저장할 데이터가 없습니다.\")\n",
        "        return\n",
        "\n",
        "    try:\n",
        "        with open(file_path, 'w', encoding='utf-8') as f:\n",
        "            f.write(f\"총 고유 바이그램 수: {len(bigram_counts)}\\n\")\n",
        "            f.write(f\"총 바이그램 빈도 합계: {sum(bigram_counts.values())}\\n\")\n",
        "            f.write(\"-\" * 50 + \"\\n\")\n",
        "\n",
        "            for bigram, count in bigram_counts.most_common():\n",
        "                f.write(f\"{bigram}: {count}\\n\")\n",
        "        print(f\"모든 결과가 '{file_path}'에 저장되었습니다.\")\n",
        "    except Exception as e:\n",
        "        print(f\"파일 저장 오류: {e}\")\n",
        "\n",
        "def main():\n",
        "    # 텍스트 파일들이 있는 디렉토리 경로 (현재 디렉토리로 설정)\n",
        "    directory_path = '.'  # 현재 디렉토리, 필요시 경로 변경\n",
        "\n",
        "    # 전체 바이그램 카운터\n",
        "    total_bigram_counts = collections.Counter()\n",
        "\n",
        "    # 처리된 파일 수 카운트\n",
        "    processed_files = 0\n",
        "\n",
        "    # 디렉토리의 모든 .txt 파일 처리\n",
        "    for filename in os.listdir(directory_path):\n",
        "        if filename.endswith('.txt'):\n",
        "            file_path = os.path.join(directory_path, filename)\n",
        "            print(f\"\\n'{filename}' 파일 처리 중...\")\n",
        "\n",
        "            # 각 파일의 바이그램 처리\n",
        "            file_bigram_counts = process_text_file(file_path)\n",
        "\n",
        "            if file_bigram_counts:\n",
        "                total_bigram_counts.update(file_bigram_counts)\n",
        "                processed_files += 1\n",
        "                print(f\"'{filename}' - 고유 바이그램 수: {len(file_bigram_counts)}\")\n",
        "\n",
        "    if processed_files == 0:\n",
        "        print(\"처리할 .txt 파일을 찾을 수 없습니다.\")\n",
        "        return\n",
        "\n",
        "    if not total_bigram_counts:\n",
        "        print(\"전체적으로 처리할 데이터가 없습니다.\")\n",
        "        return\n",
        "\n",
        "    print(f\"\\n=== 전체 결과 요약 ===\")\n",
        "    print(f\"처리된 파일 수: {processed_files}\")\n",
        "    print(f\"총 고유 바이그램 수: {len(total_bigram_counts)}\")\n",
        "    print(f\"총 바이그램 빈도 합계: {sum(total_bigram_counts.values())}\")\n",
        "\n",
        "    # 상위 20개 바이그램 콘솔 출력 (전체는 파일로 저장)\n",
        "    print(f\"\\n가장 흔한 한자 2-그램 (상위 20개):\")\n",
        "    for i, (bigram, count) in enumerate(total_bigram_counts.most_common(20), 1):\n",
        "        print(f\"{i:2d}. {bigram}: {count}\")\n",
        "\n",
        "    # 모든 결과를 파일로 저장\n",
        "    save_bigrams_to_file(total_bigram_counts)\n",
        "\n",
        "    print(f\"\\n전체 {len(total_bigram_counts)}개의 바이그램이 파일에 저장되었습니다.\")\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    main()\n"
      ],
      "metadata": {
        "id": "7mqOZQcwSCZn"
      },
      "execution_count": null,
      "outputs": []
    }
  ],
  "metadata": {
    "colab": {
      "name": "Colab 시작하기",
      "provenance": []
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}